create table if not exists container
(
    id   bigint                      not null,
    time timestamp without time zone not null default current_timestamp,
    constraint container_id primary key (id)
);

create table if not exists parameter
(
    id           bigint generated by default as identity not null,
    name         varchar,
    value        decimal,
    container_id bigint                                  not null,
    constraint parameter_id primary key (id),
    constraint parameter_container_id foreign key (container_id) references container (id) on delete cascade
);